### ISSUE TITLE
[Crash] Mod crash at start of minecraft

### ISSUE THREAD

**Issue by Anonyku05** [Cozary/Tinted-Campfires#1]
Hi, as said in the title, the game start but then crash once the mods are loaded
Launcher error: 
_The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'tintedcampfires' at 'com.cozary.tintedcampfires.TintedCampfiresFabric'!_

Crash report: https://mclo.gs/dt83SuR

**Comment by Cozary** [comment]
-Fabric Loader 1.16.5
-Fabric API 0.97.2+1.20.4

I've tried on a new instance with just the mod and the game starts.
